config/routes.rb
Rails.application.routes.draw do
  root :to => 'stockists#index'

  resources :stockists do
    member do
      get 'export'
    end
  end

  post 'calculate' => 'calculations#calculate'

  resources :imports

  get '/zipcode/:zip' => 'stockists#zip_lookup'

  get '/sync_orders', to: 'stockists#sync_orders'
  get '/total_orders', to: 'stockists#get_total_orders'

  get '/' => 'stockists#index', as: 'app'
  mount ShopifyApp::Engine, at: '/'

end

app/models/stockist.rb
class Stockist < ApplicationRecord
  belongs_to :shop
  has_many :orders
  has_many :rewards
  has_and_belongs_to_many :product_types
  accepts_nested_attributes_for :product_types
  before_save :set_country, :set_full_address, :geocode, :set_start_date
  geocoded_by :full_street_address

  def calculate_rewards
    count = 0
    Order.where({shop_id: self.shop_id}).each do |order|
      if is_reward_eligible?(order)
        puts "#{order.shopify_id} is Eligible!"
        rp = shop.last_reward_period
        reward = Reward.find_or_initialize_by({stockist_id: self.id, order_id: order.id, reward_period: rp})
        reward.amount = self.reward_for_order(order)

        if reward.save
          count = count + 1
        else
          logger.info 'REWARD SAVE FAILED!'
          logger.info reward.errors.inspect
        end
      end
    end
    self.calculated_at = Time.now
    self.save
    count
  end

  def is_reward_eligible?(order)
    unless self.latitude.blank? or order.latitude.blank?
      puts "INFO: checking eligibility for order #"+order.name+", distance is #{self.distance_to(order)}"
      if self.distance_to(order) < self.order_radius && order.created_at >= self.started_at
        if self.restricted
          order.line_items.each do |li|
            next if li.product_type.blank? || self.product_types.blank?
            if self.product_types.map{|e| e.title}.include? li.product_type
              return true
            end
          end
        else
          return true
        end
      end
      false
    end
  end

  def reward_for_order(order)
    if self.restricted
      reward = 0
      order.line_items.each do |li|
        next if li.product_type.blank? || self.product_types.blank?
        if self.product_types.map{|e| e.title}.include? li.product_type
          reward += (li.amount.to_f * self.reward_percentage.to_f) / 100.0
        end
      end
      reward
    else
      (order.total.to_f * self.reward_percentage.to_f) / 100.0
    end
  end

  def total_reward_amount
    self.rewards.sum(:amount)
  end

  def rewards_for_last_period

  end

  def export
    require 'csv'
    CSV.generate do |csv|
      column_names = ['Order', 'First Name', 'Last Name', 'Phone', 'Order Total', 'Reward Amount', 'Order Date', 'Order Distance (mi)']
      csv << column_names unless column_names.empty?
      earliest_date = latest_date = Date.today
      self.rewards.each do |r|
        o = r.order
        earliest_date = [earliest_date, o.created_at].min
        latest_date = [earliest_date, o.created_at].min
        csv << [
          o.name,
          o.first_name,
          o.last_name,
          o.phone,
          ActionController::Base.helpers.number_to_currency(o.total),
          ActionController::Base.helpers.number_to_currency(r.amount),
          o.created_at.strftime('%m/%d/%Y %H:%M'),
          r.order.distance_to(self).round(1)
        ]
      end
      2.times do
        csv << ['']
      end
      csv << ['Total:',ActionController::Base.helpers.number_to_currency(total_reward_amount)]
      csv << ['Date Range:', 'From:', earliest_date.strftime('%m/%d/%Y %H:%M'), 'To:', latest_date.strftime('%m/%d/%Y %H:%M')]
    end

  end

  def clear_rewards
    self.rewards.destroy_all
  end

  def rewards_for_last_period
    Reward.where(reward_period: shop.last_reward_period, stockist: self)
  end

  def self.import_csv(shop = Shop.last, file = "stockists.csv")
    require 'csv'

      CSV.foreach(file, quote_char: '"', col_sep: ',', row_sep: :auto, headers: true) do |row|
      if !row['Name'].blank?
        st = Stockist.create({shop_id: shop.id, name: row['Name'], address_1: row['Address'], city: row['City'], state: row['State'], postcode: row['ZIP']})
        st.order_radius = 10
        st.reward_percentage = 10
        st.product_types.destroy_all
        if !row['Product Types'].blank?
          puts "PRODUCT TYPES:"+row['Product Types'].inspect
          pts = row['Product Types'].split(',')
          puts pts.inspect
          pts.each do |pt|
            pt = pt.strip
            pt = pt.singularize
            p = ProductType.find_or_initialize_by({title: pt, shop_id: shop.id, handle: pt.gsub(' ','-')})
            p.save if p.id.nil?
            st.product_types << p
          end
          st.restricted = true
        else
          st.restricted = false
        end

        # TEMPORARY
        st.started_at = Date.today - 1.week

        if st.save

        else
          logger.info "ERROR: STOCKIST failed to save: #{st.errors.inspect}"
        end
      end
    end
  end

  def product_type_list(prefix)
    unless self.product_types.blank?
      prefix+" "+self.product_types.map{|e| e.title.pluralize}.to_sentence
    end
  end

  private

  def set_country
  end

  def set_full_address
    self.full_street_address = "#{self.address_1} #{self.address_2}, #{self.city}, #{self.state} #{self.postcode}"
  end

  def set_start_date
    self.started_at = Date.today if self.started_at.nil?
  end

end

app/controllers/stockists_controller.rb
class StockistsController < ApplicationController
  before_action :config_country, only: [:new, :edit, :update]
  before_action :shop_sync

  def index
    @stockists = Stockist.where(shop: @shop)
    @reward_period = RewardPeriod.new
    @reward_period.shop = @shop
    if @stockists.count == 0
      redirect_to action: 'new'
    end
  end

  def new
    @stockist = Stockist.new
    @countries = ['US']
    @states = ISO3166::Country.new(@countries[0]).states
  end

  def create
    @stockist = Stockist.new(stockist_params)
    if @stockist.save
      redirect_to '/stockists' and return
    else
      logger.info @stockist.errors.inspect
    end
  end

  def show
    @stockist = Stockist.find(params[:id])
    to_javascript stockist: @stockist
  end

  def edit
    @stockist = Stockist.find(params[:id])
  end

  def update
    @stockist = Stockist.find(params[:id])
    opt = @stockist.product_types.map{|e| e.id}
    if product_type_params
      @stockist.product_types.destroy_all
      product_type_params.keys.each do |pt|
        if product_type_params[pt] == "true"
          @stockist.product_types << ProductType.find_by(handle: pt)
        end
      end
    end

    if opt.sort == @stockist.product_types.map{|e| e.id}.sort
      logger.info "INFO:  PRODUCT TYPES NOT CHANGED"
    else
      logger.info "INFO:  PRODUCT TYPES CHANGED"
      @stockist.clear_rewards
      logger.info "INFO:  REMOVED EXISTING STOCKIST REWARDS"
      shop_sync
    end

    if @stockist.update(stockist_params)
      flash[:notice] = 'Stockist Updated!'
      redirect_to action: 'index' and return
    else
      render action: 'edit'
    end
  end

  def destroy
    @stockist = Stockist.find(params[:id])
    @stockist.destroy
    redirect_to action: "index"
  end

  def calculate

  end

  def export
    @stockist = Stockist.find(params[:id])
    csv = @stockist.export
    send_data csv, type: 'text/csv', filename: @stockist.name.gsub(' ','-')+".csv", disposition: "attachment" and return
  end

  def get_total_orders
    count = get_order_count
    respond_to do |format|
      format.json { render json: { count: count } }
    end
  end

  def zip_lookup
   sql = "select city,state from zcta where zip="+params[:zip]
   records_array = ActiveRecord::Base.connection.execute(sql)
   records_array.each do |r|
     render plain: r and return
   end
   render plain: '[]'
  end

  private

  def stockist_params
    params.require(:stockist).permit(
      :shop_id, :name, :address_1, :address_2, :city, :state, :postcode,
      :order_radius, :reward_percentage, :started_at, :restricted)
  end

  def product_type_params
    params.require(:product_type).permit(:shirt, :pants, :accessories)
  end

  def get_shop
    s = ShopifyAPI::Shop.current
    @shop = Shop.find_by(shopify_domain: s.myshopify_domain)
    @shopify_domain = s.domain.split('.')[0]
  end

  def get_order_count
    ShopifyAPI::Order.count
  end

  def config_country
    @countries = ['US']
    @states = ISO3166::Country.new(@countries[0]).states
  end

  def shop_sync
    OrderSyncJob.perform_later(@shop)
  end

end

app/views/stockists/_checkboxes_for_product_type.html.erb
<div class="Polaris-FormLayout__Item">
  <div class="">

    <div class="Polaris-Labelled__LabelWrapper">
      <label class="Polaris-Choice" for="Checkbox-restrict">
        <span class="Polaris-Choice__Control">
          <div class="Polaris-Checkbox" id="checkbox-restrict">
            <%= form.hidden_field :restricted, value: @stockist.restricted %>
            <input type="checkbox" class="Polaris-Checkbox__Input" aria-invalid="false" role="checkbox" aria-checked="false" value="on">
            <div class="Polaris-Checkbox__Backdrop"></div>
            <div class="Polaris-Checkbox__Icon  <%= ' checked ' if @stockist.restricted %>"  id="checkbox-restrict-icon">
              <span class="Polaris-Icon">
                <svg class="Polaris-Icon__Svg" viewBox="0 0 20 20">
                  <g fill-rule="evenodd">
                    <path d="M8.315 13.859l-3.182-3.417a.506.506 0 0 1 0-.684l.643-.683a.437.437 0 0 1 .642 0l2.22 2.393 4.942-5.327a.437.437 0 0 1 .643 0l.643.684a.504.504 0 0 1 0 .683l-5.91 6.35a.437.437 0 0 1-.642 0"></path>
                    <path d="M8.315 13.859l-3.182-3.417a.506.506 0 0 1 0-.684l.643-.683a.437.437 0 0 1 .642 0l2.22 2.393 4.942-5.327a.437.437 0 0 1 .643 0l.643.684a.504.504 0 0 1 0 .683l-5.91 6.35a.437.437 0 0 1-.642 0"></path>
                  </g>
                </svg>
              </span>
            </div>
          </div>
        </span>
        <span class="Polaris-Choice__Label">Restrict By Product Type?</span>
      </label>
    </div>
    <div id="product-types">
      <% types.each do |t| %>
        <div>
          <label class="Polaris-Choice" for="Checkbox-<%=t.handle%>">
            <span class="Polaris-Choice__Control">
              <div class="Polaris-Checkbox">

                <input type="hidden" name="product_type[<%=t.handle%>]" value="false" id="stockist_<%=t.handle%>"/>

                <input type="checkbox" id="checkbox-<%=t.handle%>" class="Polaris-Checkbox__Input product-type-checkbox" aria-invalid="false" role="checkbox" aria-checked="false" value="on">
                <div class="Polaris-Checkbox__Backdrop"></div>
                <div class="Polaris-Checkbox__Icon   <%= ' checked ' if @stockist.product_types.map{|e| e.handle}.include? t.handle %>"  id="checkbox-<%=t.handle%>-icon">
                  <span class="Polaris-Icon">
                    <svg class="Polaris-Icon__Svg" viewBox="0 0 20 20">
                      <g fill-rule="evenodd">
                        <path d="M8.315 13.859l-3.182-3.417a.506.506 0 0 1 0-.684l.643-.683a.437.437 0 0 1 .642 0l2.22 2.393 4.942-5.327a.437.437 0 0 1 .643 0l.643.684a.504.504 0 0 1 0 .683l-5.91 6.35a.437.437 0 0 1-.642 0"></path>
                        <path d="M8.315 13.859l-3.182-3.417a.506.506 0 0 1 0-.684l.643-.683a.437.437 0 0 1 .642 0l2.22 2.393 4.942-5.327a.437.437 0 0 1 .643 0l.643.684a.504.504 0 0 1 0 .683l-5.91 6.35a.437.437 0 0 1-.642 0"></path>
                      </g>
                    </svg>
                  </span>
                </div>
              </div>
            </span>
            <span class="Polaris-Choice__Label"><%= t.title %></span>
          </label>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/stockists/_new_text_input.html.erb
<div class="Polaris-FormLayout__Item">
  <div class="">
    <div class="Polaris-Labelled__LabelWrapper">
      <div class="Polaris-Label"><label id="TextField8Label" for="TextField8" class="Polaris-Label__Text"><%= label %></label></div>
    </div>
    <div class="Polaris-TextField">

      <%= form.text_field field, class: 'Polaris-TextField__Input', required: (label != 'Address 2') %>

      <div class="Polaris-TextField__Backdrop"></div>
    </div>
  </div>
</div>

app/views/stockists/_stockist_form.html.erb
<%= render 'layouts/flash_messages' if !flash.empty? %>
<%= form_for @stockist do |f| %>
  <%= f.hidden_field :shop_id, value: @shop.id %>
  <div class="container-fluid">

    <div class="row">
      <div class="col-xs-6">

        <div class="Polaris-FormLayout new-stockist">
          <div class="col-xs-12">
            <%= render 'new_text_input', {form: f, field: :name, label: 'Stockist Name'} %>
          </div>

          <div class="col-xs-6">
            <div class="Polaris-FormLayout__Item">

              <div class="">
                <div class="Polaris-Labelled__LabelWrapper">
                  <div class="Polaris-Label"><label id="Select1Label" for="Select1" class="Polaris-Label__Text">Country</label></div>
                </div>
                <div class="Polaris-Select Polaris-Select--placeholder"><select id="Select1" class="Polaris-Select__Input" aria-invalid="false"><option value="US">US</option></select>
                  <div
                    class="Polaris-Select__Icon"><span class="Polaris-Icon"><svg class="Polaris-Icon__Svg" viewBox="0 0 20 20"><path d="M13 8l-3-3-3 3h6zm-.1 4L10 14.9 7.1 12h5.8z" fill-rule="evenodd"></path></svg></span></div>
                  <div class="Polaris-Select__Backdrop"></div>
                </div>
              </div>

            </div>
          </div>

          <div class="col-xs-6">
            <%= render 'new_text_input', {form: f, field: :postcode, label: 'Zip/Post Code'} %>
          </div>
          <div class="col-xs-12">
            <%= render 'new_text_input', {form: f, field: :address_1, label: 'Address'} %>
          </div>
          <div class="col-xs-12">
            <%= render 'new_text_input', {form: f, field: :address_2, label: 'Address 2'} %>
          </div>
          <div class="col-xs-6">
            <%= render 'new_text_input', {form: f, field: :city, label: 'City'} %>
          </div>
          <div class="col-xs-6">
            <div class="Polaris-FormLayout__Item">

              <div class="">
                <div class="Polaris-Labelled__LabelWrapper">
                  <div class="Polaris-Label"><label id="Select1Label" for="Select1" class="Polaris-Label__Text">State</label></div>
                </div>
                <div class="Polaris-Select Polaris-Select--placeholder">
                  <select id="stockist_state" name="stockist[state]" class="Polaris-Select__Input">
                    <option value="">Select State</option>
                    <% @states.each do |s| %>
                      <% next if s[1].name.include? 'Armed Forces' %>
                      <option value="<%=s[0]%>" <%= "selected" if @stockist.state == s[0] %>><%=s[1].name%></option>
                    <% end %>
                  </select>
                  <div
                    class="Polaris-Select__Icon"><span class="Polaris-Icon"><svg class="Polaris-Icon__Svg" viewBox="0 0 20 20"><path d="M13 8l-3-3-3 3h6zm-.1 4L10 14.9 7.1 12h5.8z" fill-rule="evenodd"></path></svg></span></div>
                  <div class="Polaris-Select__Backdrop"></div>
                </div>
              </div>

            </div>
          </div>

          <div class="col-sm-6">
            <%= render 'new_text_input', {form: f, field: :order_radius, label: 'Order Radius (miles)'} %>
          </div>
          <div class="col-sm-6">
            <%= render 'new_text_input', {form: f, field: :reward_percentage, label: 'Reward Percentage'} %>
          </div>
          <div class="col-sm-6">
            <div class="Polaris-FormLayout__Item">
              <div class="">
                <div class="Polaris-Labelled__LabelWrapper">
                  <div class="Polaris-Label"><label id="TextField8Label" for="TextField8" class="Polaris-Label__Text">Start Date for Rewards</label></div>
                </div>
                <div class="Polaris-TextField">
                  <%= f.text_field :started_at, value: (@stockist.started_at.nil?) ? Date.today.strftime('%m/%d/%Y') : @stockist.started_at.strftime('%m/%d/%Y'), class: 'Polaris-TextField__Input', data: { provide: 'datepicker' } %>
                  <div class="Polaris-TextField__Backdrop"></div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-sm-6" style="height: 80px;">

          </div>
          <div class="col-sm-6">
            <%= render 'checkboxes_for_product_type', {form: f, types: ProductType.all, label: 'Restrict by Product Type?'} %>
          </div>
        </div>
        <div class="submit-btns">
          <button id="import-csv" class="Polaris-Button Polaris-Button--secondary new-submit"><span class="Polaris-Button__Content"><span> Import CSV </span></span></button>
          <button type="submit" class="Polaris-Button Polaris-Button--primary new-submit"><span class="Polaris-Button__Content"><span><%= (['edit', 'update'].include? action_name) ? 'Save' : 'Create' %> Stockist</span></span></button>
        </div>

      </div>

      <div class="col-sm-6">
        <div id="map"></div>
      </div>

    </div>
  </div>

<% end %>

app/views/stockists/edit.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({
        title: "Stockists",
        icon: "<%= asset_path('favicon.ico') %>",
        buttons: {
          primary: {
            label: 'Back to Stockists',
            message: 'save',
            href: 'https://stockistrewards.com/stockists'
          },
          secondary: {
            label: 'Help',
            message: 'help',
            href: 'mailto:info@mauinewyork.com'
          }
        }
      });
    });
    ShopifyApp.Bar.initialize
  </script>
<% end %>

<%= render 'stockist_form' %>

app/views/stockists/index.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({
        title: "Stockists",
        icon: "<%= asset_path('favicon.ico') %>",
        buttons: {
          primary: {
            label: 'New Stockist',
            message: 'save',
            href: 'https://stockistrewards.com/stockists/new'
          },
          secondary: {
            label: 'Help',
            message: 'help',
            href: 'mailto:info@mauinewyork.com'
          }
        }
      });
    });
    ShopifyApp.Bar.initialize
  </script>
<% end %>
<div class="container-fluid">
  <%= render 'shared/flash' if !flash.empty? %>
  <div class="row">
      <div class="Polaris-Card">

        <ul class="Polaris-ResourceList">
          <li class="Polaris-ResourceList__ItemWrapper" style="height: 100px; margin: 20px 0 0 20px;">

            <%= form_for @reward_period, url: '/calculate', id: 'calc' do |f| %>
              <div class="col-sm-2">
                <div class="Polaris-Labelled__LabelWrapper">
                  <div class="Polaris-Label"><label id="TextField8Label" for="TextField8" class="Polaris-Label__Text">Start Date</label></div>
                </div>
                <div class="Polaris-TextField">
                  <%= f.text_field :start_date, value: (@reward_period.start_date.nil?) ? @shop.earliest_start_date.strftime('%m/%d/%Y') : @reward_period.start_date.strftime('%m/%d/%Y'), class: 'Polaris-TextField__Input', data: { provide: 'datepicker' } %>
                  <div class="Polaris-TextField__Backdrop"></div>
                </div>
              </div>

              <div class="col-sm-2">
                <div class="Polaris-Labelled__LabelWrapper">
                  <div class="Polaris-Label"><label id="TextField8Label" for="TextField8" class="Polaris-Label__Text">End Date</label></div>
                </div>
                <div class="Polaris-TextField">
                  <%= f.text_field :end_date, value: (@reward_period.start_date.nil?) ? Date.today.strftime('%m/%d/%Y') : @reward_period.end_date.strftime('%m/%d/%Y'), class: 'Polaris-TextField__Input', data: { provide: 'datepicker' } %>
                  <div class="Polaris-TextField__Backdrop"></div>
                </div>
              </div>

              <div class="col-sm-6">
                <div class="Polaris-ButtonGroup__Item">
                  <button type="button" class="Polaris-Button Polaris-Button--primary calc-btn"><span class="Polaris-Button__Content"><span>Calculate</span></span></button>
                </div>
              </div>

            <% end %>

          </li>
          <% @stockists.each_with_index do |s,ii| %>
            <li class="Polaris-ResourceList__ItemWrapper">
              <div class="Polaris-ResourceList__Item Polaris-ResourceList__Item--link">
                <div class="container-fluid">
                  <div class="row product-video-row">
                    <div class="col-sm-6">
                      <div class="stockist-spacer">
                        <p class="Polaris-ResourceList__AttributeOne"><%= s.name %></p>
                        <div class="Polaris-ResourceList__AttributeTwo"><%= s.address_1 %></div>
                        <div class="Polaris-ResourceList__AttributeTwo"><%= s.address_2 %></div>
                        <div class="Polaris-ResourceList__AttributeTwo"><%= s.city %>, <%= s.state %>&nbsp;&nbsp;<%= s.postcode %></div>
                        <div class="Polaris-ResourceList__Badge">
                          <span class="Polaris-Badge"><%= s.reward_percentage %>% REWARD</span>
                          <span><%= s.product_type_list("for") %></span>
                        </div>
                        <div class="Polaris-ResourceList__Badge">Shipped within <span class="Polaris-Badge"><%= s.order_radius%> Miles</span></div>
                        <div class="Polaris-ResourceList__AttributeThree"><span class="Polaris-TextStyle--variationSubdued">Started <%=time_ago_in_words(s.started_at) %> ago</span></div>
                      </div>
                    </div>
                    <div class="col-sm-3">
                      <% if s.rewards.any? %>
                        <div><span class="eligible-order-count"><%= rc = s.rewards.count %></span> Order<%="s" if rc > 0 %> Eligible For Reward</div>
                        <div><span class="eligible-amount"><%= number_to_currency s.total_reward_amount %></span> To Be Paid</div>
                        <%= link_to s, class: 'Polaris-Button view-orders', data: { polaris: { unstyled: true } } do %>
                          <span class="Polaris-Button__Content product-view-link">View Orders</span>
                        <% end %>
                        <%= link_to export_stockist_path(s), class: 'Polaris-Button view-orders', data: { polaris: { unstyled: true } } do %>
                          <span class="Polaris-Button__Content product-view-link" href="/stockists/<%=s.id%>/orders/export">Export Orders</span>
                        <% end %>
                      <% elsif s.shop.synced_at.blank? %>
                        <% if ii == 0 %>
                          <div><span class="eligible-order-count">Syncing Orders...</div>
                        <% end %>
                      <% elsif s.calculated_at.blank? %>
                        <div><span class="eligible-order-count">Calculating Rewards...</div>
                      <% else %>
                        <div><span class="eligible-order-count">No Eligible Orders Yet</div>
                      <% end %>
                    </div>
                    <div class="col-sm-3">
                      <div class="Polaris-ButtonGroup product-links">
                        <div class="Polaris-ButtonGroup__Item">
                          <%= link_to [:edit, s], class: 'Polaris-Button', data: { polaris: { unstyled: true } } do %>
                            <span class="Polaris-Button__Content product-view-link">Edit</span>
                          <% end %>
                        </div>
                        <div class="Polaris-ButtonGroup__Item">
                          <%= link_to s,  method: :delete, data: { confirm: 'Are you sure?' }, class: 'Polaris-Button' do %>
                            <span class="Polaris-Icon">
                              <svg viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M16 6H4a1 1 0 1 0 0 2h1v9a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V8h1a1 1 0 1 0 0-2zM9 4a1 1 0 1 1 0-2h2a1 1 0 1 1 0 2H9zm2 12h2V8h-2v8zm-4 0h2V8H7v8z" fill="#31373D" fill-rule="evenodd"/></svg>
                            </span>
                          <% end %>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/stockists/new.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({
        title: "New Stockist",
        icon: "<%= asset_path('favicon.ico') %>",
        buttons: {
          primary: {
            label: 'Back to Stockists',
            message: 'save',
            href: '<%= request.protocol+request.host_with_port %>/stockists'
          },
          secondary: [{
            label: 'Help',
            message: 'help',
            href: 'mailto:info@mauinewyork.com'
          }]
        }
      });
    });

  </script>
<% end %>

<%= render 'stockist_form' %>

app/views/stockists/show.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({
        title: "Stockist Detail: <%= @stockist.name %>",
        icon: "<%= asset_path('favicon.ico') %>",
        buttons: {
          primary: {
            label: 'Edit Stockist',
            message: 'save',
            href: 'https://stockistrewards.com/stockists/<%=@stockist.id%>/new'
          },
          secondary: {
            label: 'Help',
            message: 'help',
            href: 'mailto:info@mauinewyork.com'
          }
        }
      });
    });
    ShopifyApp.Bar.initialize
  </script>
<% end %>
<div class="container-fluid">

  <div class="row">
    <div class="col-xs-12">
      <div class="col-xs-6">
        <%= @stockist.name %>
        <%= @stockist.full_street_address %>
      </div>

      <div class="col-xs-6">
        <div id="map"></div>
      </div>
    </div>

    <div class="col-xs-12">

      <div class="Polaris-Card">
        <ul class="Polaris-ResourceList">
          <% @stockist.rewards.each_with_index do |r, i| %>
            <li class="Polaris-ResourceList__ItemWrapper">
              <div class="Polaris-ResourceList__Item Polaris-ResourceList__Item--link"><a aria-describedby="ResourceListItem<%= i+1 %>" class="Polaris-ResourceList__Link" href="#" data-polaris-unstyled="true"></a>
                <div class="Polaris-ResourceList__Container" id="ResourceListItem<%= i+1 %>">
                  <div class="Polaris-ResourceList__Content">
                    <div class="Polaris-ResourceList__Attributes">
                      <p class="Polaris-ResourceList__AttributeOne">Order #<%= r.order.name %> Total: <%= number_to_currency(r.order.total) %>  Reward: <%= number_to_currency(r.amount) %></p>
                      <p class="Polaris-ResourceList__AttributeOne">Customer: <%= r.order.first_name %> </p>
                      <div class="Polaris-ResourceList__AttributeTwo" style="text-align:center">
                        <%= r.order.full_street_address %> (<%= r.order.distance_to(@stockist).round(1) %> Miles Away)
                      </div>
                      <div class="Polaris-ResourceList__AttributeThree"></div>
                      <div class="Polaris-ResourceList__AttributeFour"><span class="Polaris-TextStyle--variationSubdued"><%= time_ago_in_words(r.order.created_at) %> Ago</span></div>
                    </div>
                  </div>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>

    </div>
  </div>

</div>